name: RC
on:
  release:
    types: [published]

jobs:
  npm-release:
    uses: salesforcecli/github-workflows/.github/workflows/npmPublish.yml@main
    secrets: inherit
    with:
      tag: latest-rc
      ctc: true
      githubTag: ${{ github.event.release.tag_name }}

  pack-verify-upload-tarballs:
    needs: [npm-release]
    uses: salesforcecli/github-workflows/.github/workflows/tarballs.yml@main
    with:
      upload: true
      cli: sf
      version: ${{ github.event.release.tag_name }}
      channel: stable-rc
    secrets: inherit

  archives-verify:
    runs-on: ubuntu-latest
    needs: [pack-verify-upload-tarballs]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - run: npm install -g @salesforce/plugin-release-management --omit=dev
      - run: sf-release cli:versions:inspect -c stable-rc -l archive --cli sf

  pack-upload-mac:
    needs: [pack-verify-upload-tarballs]
    uses: salesforcecli/github-workflows/.github/workflows/packUploadMac.yml@main
    with:
      cli: sf
      version: ${{ github.event.release.tag_name }}
      channel: stable-rc
    secrets: inherit
    
  # The rename-mac-pkg job is only needed as long as the developer site is linking to the old sfdx.pkg file and the mac signing job is only signing the old file as well.
  # It can be removed once those are updated to use the new name, sfdx-x64.pkg.
  rename-mac-pkg:
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_EC2_METADATA_DISABLED: true
    needs: [macos]
    steps:
      - uses: salesforcecli/github-workflows/.github/actions/renameMacPkg@main
        with:
          cli: sf
          channel: stable-rc

  pack-upload-win:
    needs: [pack-verify-upload-tarballs]
    uses: salesforcecli/github-workflows/.github/workflows/packUploadWindows.yml@main
    with:
      cli: sf
      version: ${{ github.event.release.tag_name }}
      channel: stable-rc
    secrets: inherit

  Post-RC-to-Slack:
    runs-on: ubuntu-latest
    needs: [pack-verify-upload-tarballs, npm-release, pack-upload-win, pack-upload-mac]
    steps:
      - name: Announce RC Workflow
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RC_ANNOUNCEMENT_WORKFLOW_WEBHOOK }}
        with:
          payload: |
            {
              "cli": "sf",
              "npm-package": "@salesforce/cli",
              "version": "${{ github.event.release.tag_name }}"
            }
