name: ut and tarballs

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ut-tarballs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yarn-lockfile-check:
    uses: salesforcecli/github-workflows/.github/workflows/lockFileCheck.yml@main

  ut:
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@main
    secrets: inherit

  tarballs:
    uses: salesforcecli/github-workflows/.github/workflows/tarballs.yml@main
    secrets: inherit

  tarballs-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - uses: salesforcecli/github-workflows/.github/actions/yarnInstallWithRetries@main
      - name: pack tarballs
        uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd
        with:
          max_attempts: 3
          command: yarn pack:tarballs
          retry_on: error
          timeout_minutes: 60
      - run: yarn pack:verify
      - run: yarn test:smoke-unix

  artifacts:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - run: yarn install
      - run: npm install -g @salesforce/plugin-release-management
      - run: yarn test:deprecation-policy
