name: ut and tarballs

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  stampy-upload:
    uses: salesforcecli/github-workflows/.github/workflows/stampyUpload.yml@sm/stampy
    with:
      version: 2.8.8
      cli: sf
      clipkg: '@salesforce/cli'
